language: erlang
otp_release:
  - 21.0.4
  - 20.3.8.2
  - 19.3
  - 18.3
  - 17.4
sudo: false
script:
    - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
    - ./rebar3 do compile, dialyzer, eunit
